spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    username: min
    password: alsdud6038
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  #jackson:
   # deserialization: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace